Repository CS2103-AY1819S1-W13-2/main, pull requests merged in 2018-10, with the labels that each got.

#10 add aliases for all commands
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Enhancement

#60 Add command for adding events and basic Event class
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/event/Event.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/ScheduledEventBuilder.java
  src/test/java/seedu/address/testutil/ScheduledEventUtil.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: status.Ongoing, type.Enhancement, type.Story

#78 update AboutUs.adoc to reflect new images
  docs/AboutUs.adoc
Labels: type.Task

#80 update contact info
  docs/ContactUs.adoc
Labels: type.Task

#85 add import contacts csv file
  src/test/data/ImportContactsTest/importContacts.csv
Labels: priority.High, type.Enhancement

#83 Add event classes and update test cases
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventAddress.java
  src/main/java/seedu/address/model/event/EventDate.java
  src/main/java/seedu/address/model/event/EventDescription.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/EventTime.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/model/event/EventAddressTest.java
  src/test/java/seedu/address/model/event/EventDateTest.java
  src/test/java/seedu/address/model/event/EventDescriptionTest.java
  src/test/java/seedu/address/model/event/EventNameTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/EventTimeTest.java
  src/test/java/seedu/address/testutil/ScheduledEventBuilder.java
  src/test/java/seedu/address/testutil/ScheduledEventUtil.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: status.Ongoing, type.Enhancement

#64 ImportContacts command
  src/main/java/seedu/address/logic/commands/ImportContactsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ImportContactsCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/ImportContactsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: status.Ongoing, type.Enhancement

#89 add notification class and call it from UiManager
  src/main/java/seedu/address/ui/NotificationWindow.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: status.Ongoing, type.Enhancement

#93 ImportContacts.csv: Add test data
  src/test/data/ImportContactsTest/EmptyImportContacts.csv
  src/test/data/ImportContactsTest/ImportContacts.csv
  src/test/data/ImportContactsTest/InvalidImportContacts.csv
Labels: priority.High, type.Enhancement, type.Story

#84 update `AboutUs` with empty project portfolios for each member
  docs/AboutUs.adoc
  docs/team/cjiefeng.adoc
  docs/team/kaitingpeck.adoc
  docs/team/pratyayj.adoc
  docs/team/ryantanwk.adoc
  docs/team/yap666y.adoc
Labels: type.Task

#94 Readcontact branch
  src/main/java/seedu/address/logic/commands/ImportContactsCommand.java
  src/test/java/seedu/address/logic/commands/ImportContactsCommandTest.java
Labels: priority.High, type.Enhancement, type.Story

#90 implement notification class
  src/main/java/seedu/address/ui/NotificationWindow.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: status.Ongoing, type.Enhancement

#99 update user guide
  docs/UserGuide.adoc
  docs/images/add-event_new-event.PNG
Labels: type.Task

#98 Update developer guide for feature coming in v2.0
  docs/DeveloperGuide.adoc
Labels: type.Task

#97 Replace Ui mockup with actual screenshot
  docs/images/Ui.png
Labels: type.Task

#95 Add functionality to check for event clashes
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/event/exceptions/EventClashException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/UniqueEventListTest.java
Labels: type.Enhancement, type.Story

#101 DevelopGuide.adoc: Add Import Contacts Implementation
  docs/DeveloperGuide.adoc
  docs/images/ImportContactsSequenceDiagram.PNG
Labels: type.Task

#102 Add 'add events' feature documentation
  docs/DeveloperGuide.adoc
  docs/images/Event.png
  docs/images/add-event-component.png
  docs/images/add-event-event-trigger.png
Labels: priority.High, type.Task

#103 update userguide and devguide with notifications
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.High, type.Enhancement

#75 Add Faculty, modify Person classes and basic implementation of Google Maps display
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Faculty.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAndEventsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/ErrorDialogGuiTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: status.Ongoing, type.Story

#106 fix image display
  docs/DeveloperGuide.adoc
Labels: type.Task

#122 add reposense config file
  .gitignore
  _reposense/config.json
Labels: type.Task

#118 Temporary fix to test cases
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: type.Bug

#123 Update authorname for reposense
  _reposense/config.json
Labels: priority.High, type.Task

#115 implement empty favourite command and functional enable/disable notification w/o test cases
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/NotificationCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FavouriteCommandParser.java
  src/main/java/seedu/address/logic/parser/NotificationCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NotificationWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: status.Ongoing, type.Enhancement, type.Task

#116 fix exception on exit app
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TabPanel.java
Labels: type.Bug

#132 Add Faculty field to PersonCard display
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/guitests/guihandles/PersonCardHandle.java
Labels: priority.High, type.Task

#121 Create deleteEvent command
  docs/team/cjiefeng.adoc
  docs/team/johndoe.adoc
  docs/team/kaitingpeck.adoc
  docs/team/pratyayj.adoc
  docs/team/ryantanwk.adoc
  docs/team/yap666y.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/ListEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/EventNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAndEventsAddressBook.xml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/ListEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/event/UniqueEventListTest.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.Medium, type.Enhancement, type.Story

#131 Update csv file data
  src/test/data/ImportContactsTest/ImportContacts.csv
Labels: priority.High

#128 implement favourite command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/parser/FavouriteCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, type.Enhancement

#136 Checkstyle and SampleDataUtil changes
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/LocationDisplayPanel.java
Labels: type.Bug

#133 Adding to help message and UserGuide documentation
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: priority.Low

#138 Add Event `Tag` field in `Event`
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/add-event-tag_new-event-tag.PNG
  docs/images/add-event_new-event.PNG
  docs/images/delete-event.PNG
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/model/AddressBookChangedEvent.java
  src/main/java/seedu/address/commons/events/model/AddressBookEventTagChangedEvent.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedEvent.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TabPanel.java
  src/main/resources/view/EventCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/EventListView.css
  src/test/data/XmlAddressBookStorageTest/invalidAndValidAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidEventAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/duplicateEventAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalAddressBook.xml
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/storage/XmlAdaptedEventTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/ScheduledEventBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, type.Enhancement, type.Story

#141 Update developer guide
  docs/images/Event.png
  docs/images/add-event-component.png
  docs/images/add-event-event-trigger.png
  docs/images/add-event_logic-model.png
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
Labels: priority.High, type.Task
