Repository CS2103-AY1819S1-W13-2/main, pull requests merged in 2018-11, with the labels that each got.

#174 Autocomplete command
  docs/UserGuide.adoc
  src/main/java/seedu/address/ui/CommandBox.java
Labels: priority.Medium, type.Enhancement

#175 FindEvent based on event tags
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/ui/EventPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/AddEventTagCommand.java
  src/main/java/seedu/address/logic/commands/FindEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindEventCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/event/EventTagMatchesKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/logic/commands/AddEventTagCommandTest.java
  src/test/java/seedu/address/logic/commands/FindEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddEventTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindEventCommandParserTest.java
  src/test/java/seedu/address/model/event/EventTagMatchesKeywordsPredicateTest.java
Labels: priority.High, type.Bug

#173 Bug fixes for PE dry run
  docs/UserGuide.adoc
  docs/images/delete-event-after.PNG
  docs/images/delete-event-before.PNG
  docs/images/delete-event.PNG
  docs/images/find-event-before.PNG
  docs/images/find-event-lecture-class.PNG
  docs/images/find-event-lecture.PNG
  src/main/java/seedu/address/commons/events/ui/EventPanelDisplayChangedEvent.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/TabPanel.java
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/EventListView.css
Labels: type.Task

#178 Update developer guide
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Event.png
  docs/images/add-event-tag_logic-model.png
  docs/images/add-event_logic-model.png
  docs/images/autocomplete-ad.png
  docs/images/delete-event_logic-model.png
  docs/images/tabPanel.png
  docs/images/ui-display-ad.png
  docs/team/kaitingpeck.adoc
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Task

#185 User guide import contacts
  docs/UserGuide.adoc
  docs/images/import-contacts-as-google-csv.PNG
Labels: priority.High

#186 Random generation of meeting location
  src/main/java/seedu/address/logic/EmbedGoogleMaps.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/GenerateLocationCommand.java
  src/main/java/seedu/address/logic/parser/GenerateLocationCommandParser.java
Labels: priority.High

#193 Jack ppp
  docs/team/cjiefeng.adoc
Labels: priority.High

#192 Importcontacts documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ImportContactsSequenceDiagram.PNG
Labels: priority.High

#135 solve compatibility of notification/favourite with undo/redo
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/ui/TabPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/NotificationCommand.java
  src/main/java/seedu/address/logic/commands/ToggleCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/NotificationCommandParser.java
  src/main/java/seedu/address/logic/parser/ToggleCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TabPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventTagCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportContactsCommandTest.java
  src/test/java/seedu/address/logic/commands/NotificationCommandTest.java
  src/test/java/seedu/address/logic/parser/FavouriteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NotificationCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.High

#191 Add tests to cover newly added classes and modified functionality
  src/main/java/seedu/address/logic/EmbedGoogleMaps.java
  src/main/java/seedu/address/logic/commands/GenerateLocationCommand.java
  src/main/java/seedu/address/logic/commands/ShowLocationCommand.java
  src/main/java/seedu/address/ui/LocationDisplayPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/events_plus.png
  src/test/java/seedu/address/logic/EmbedGoogleMapsTest.java
  src/test/java/seedu/address/logic/commands/GenerateLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowLocationCommandTest.java
  src/test/java/seedu/address/model/person/FacultyTest.java
Labels: priority.High

#195 User and developer guide changes
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.Task

#197 Update showLocation sequence diagram
  docs/images/showLocation_EventsCenter_seqDiagram.PNG
Labels: priority.High

#194 update documentation for toggle command & resolve failing legacy tests
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.Medium

#202 update ppp
  docs/DeveloperGuide.adoc
Labels: type.Task

#198 Add Pratyay PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/pratyayj.adoc
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#203 Update Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/kaitingpeck.adoc
Labels: type.Task

#205 Add tests and extra condition checking in UniqueEventList
  src/main/java/seedu/address/logic/commands/EditEventAddressCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/model/event/EventNameContainsKeywordsPredicateTest.java
Labels: priority.Medium

#207 Update Ryan's PPP
  docs/team/ryantanwk.adoc
Labels: priority.High

#208 Update Ryan's PPP
  docs/team/ryantanwk.adoc
Labels: priority.High

#209 Update Jack PPP
  docs/team/cjiefeng.adoc
Labels: priority.High
